### ISSUE TITLE
Changing User

### ISSUE THREAD

**Issue by WynBoon** [costastf/locationsharinglib#16]
I am using HomeAssistant, I added the google_maps platform to the Configuration file and set it all up. After the boot, the Pi requested access to my account. After changing the account to the new created user as per the install notes, the new user does not come up in the list of Device Activity and does not seem to be loaded in HA. 

The strange thing is that when i look at the Device activity of the original account I entered, the last seen time was only 30min ago. This leads me to believe that the Setup has not accepted the new user credentials. 

When looking at the log file I get:
Error setting up platform google_maps:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/components/device_tracker/__init__.py", line 184, in async_setup_platform
    disc_info)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/device_tracker/google_maps.py", line 36, in setup_scanner
    scanner = GoogleMapsScanner(hass, config, see)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/device_tracker/google_maps.py", line 55, in __init__
    self._update_info()
  File "/usr/lib/python3.6/site-packages/homeassistant/components/device_tracker/google_maps.py", line 67, in _update_info
    for person in self.service.get_all_people():
  File "/usr/lib/python3.6/site-packages/locationsharinglib/locationsharinglib.py", line 292, in get_all_people
    return self._get_data()
  File "/usr/lib/python3.6/site-packages/cachetools/__init__.py", line 46, in wrapper
    v = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/locationsharinglib/locationsharinglib.py", line 283, in _get_data
    output = json.loads(response.text.split("'", 1)[1])
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by costastf** [comment]
Did you remove the actual cookies file of the initial account? if not it will be picked up and the new account will never show up. If the cookies are present the component favors them over the credentials and uses them. So if you switched accounts you need to remove the old cookies file and then it will create a new one for that account.I am closing this since I think that this is what your issue is but feel free to open it again if it is something else.

**Comment by costastf** [comment]
please note that the cookies file is called .google_maps_location_sharing.cookies with a dot in front which makes it hidden in linux systems.
