### ISSUE TITLE
UnboundLocalError: local variable 'data' referenced before assignment

### ISSUE THREAD

**Issue by chilicheech** [costastf/locationsharinglib#24]
Version 2.0.7

When running this in a python3 console:
```
from locationsharinglib import Service
service = Service('user@gmail.com', 'password', cookies_file='.google_maps_location_sharing.cookies')
for person in service.get_all_people():
    print(person)
```
I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/locationsharinglib/locationsharinglib.py", line 393, in get_all_people
    people = self.get_shared_people() + [self.get_authenticated_person()]
  File "/usr/local/lib/python3.6/site-packages/locationsharinglib/locationsharinglib.py", line 360, in get_shared_people
    output = self._get_data()
  File "/usr/local/lib/python3.6/site-packages/cachetools/__init__.py", line 46, in wrapper
    v = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/locationsharinglib/locationsharinglib.py", line 354, in _get_data
    return data
UnboundLocalError: local variable 'data' referenced before assignment
```
What gives?

**Comment by jedi7** [comment]
I see this fixed in master version

**Comment by costastf** [comment]
I guess that this can be closed...
