### ISSUE TITLE
Error setting up platform google maps

### ISSUE THREAD

**Issue by jkhiii** [costastf/locationsharinglib#32]
I have not been able to get google maps presence detection to work.  I am using hassio on a Rasberry Pi 3. I get the following error.  I have also tried life 360 and get a similar error. 
`Error setting up platform google_maps
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/device_tracker/__init__.py", line 183, in async_setup_platform
    disc_info)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/device_tracker/google_maps.py", line 44, in setup_scanner
    scanner = GoogleMapsScanner(hass, config, see)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/device_tracker/google_maps.py", line 63, in __init__
    hass.config.path(CREDENTIALS_FILE))
  File "/usr/local/lib/python3.6/site-packages/locationsharinglib/locationsharinglib.py", line 370, in __init__
    cookies_file=cookies_file)
  File "/usr/local/lib/python3.6/site-packages/locationsharinglib/locationsharinglib.py", line 194, in __init__
    if cookies_file and self._validate_cookie(cookies_file):
  File "/usr/local/lib/python3.6/site-packages/locationsharinglib/locationsharinglib.py", line 205, in _validate_cookie
    self._session.cookies = pickle.load(cfile)
EOFError: Ran out of input`

**Comment by costastf** [comment]
Have you tried the library independent of HA as mentioned in the documentation? What is the result of that?

**Comment by costastf** [comment]
Closing this as there is no extra info on the issue.
