### ISSUE TITLE
InvalidData exception after update

### ISSUE THREAD

**Issue by WillDHB** [costastf/locationsharinglib#39]
I recently upgraded from 2.0.11 to 3.0.3, and now I'm receiving the following error:

Traceback (most recent call last):
[omitted irrelevant portion of stack]
  File "C:\Users\Will\davis\.tox\py36-prod-plat_windows\lib\site-packages\locationsharinglib\locationsharinglib.py", line 459, in get_all_people
    people = self.get_shared_people() + [self.get_authenticated_person()]
  File "C:\Users\Will\davis\.tox\py36-prod-plat_windows\lib\site-packages\locationsharinglib\locationsharinglib.py", line 451, in get_authenticated_person
    None,
  File "C:\Users\Will\davis\.tox\py36-prod-plat_windows\lib\site-packages\locationsharinglib\locationsharinglib.py", line 95, in __init__
    self._populate(data)
  File "C:\Users\Will\davis\.tox\py36-prod-plat_windows\lib\site-packages\locationsharinglib\locationsharinglib.py", line 113, in _populate
    raise InvalidData
locationsharinglib.locationsharinglibexceptions.InvalidData

Nothing has changed except the version, and downgrading again eliminates the exception.

**Comment by costastf** [comment]
Do you mind running it in debug and pasting the output making sure that you strip out all personal info?

**Comment by WillDHB** [comment]
Sure.  What do you mean by "running it in debug"?

**Comment by costastf** [comment]
If you run the cli with --help as an argument you will see the extra option there. I have add a logging option. You can run it with "-L DEBUG" and provide all the transaction.

**Comment by WillDHB** [comment]
Ah, so debug logging then.  I'm actually not using the cli, which doesn't seem to work for me.  I pull the cookies from my browser:

`   cj = browser_cookie3.firefox()
    rcj = requests.cookies.RequestsCookieJar()
    rcj.update(cj)
    with open(name, 'wb') as fp:
        pickle.dump(rcj, fp)
`
...and then I just load that file into the service.

I ran it again in a separate test script, and noticed I missed part of the stack trace before:

```
Traceback (most recent call last):
  File "c:\temp\locenv\lib\site-packages\locationsharinglib\locationsharinglib.py", line 109, in _populate
    self._charging = data[13][0]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lshar.py", line 65, in <module>
    main()
  File "lshar.py", line 55, in main
    people = get_people(cfile)
  File "lshar.py", line 45, in get_people
    return service.get_all_people()
  File "c:\temp\locenv\lib\site-packages\locationsharinglib\locationsharinglib.py", line 459, in get_all_people
    people = self.get_shared_people() + [self.get_authenticated_person()]
  File "c:\temp\locenv\lib\site-packages\locationsharinglib\locationsharinglib.py", line 451, in get_authenticated_person
    None,
  File "c:\temp\locenv\lib\site-packages\locationsharinglib\locationsharinglib.py", line 95, in __init__
    self._populate(data)
  File "c:\temp\locenv\lib\site-packages\locationsharinglib\locationsharinglib.py", line 113, in _populate
    raise InvalidData
locationsharinglib.locationsharinglibexceptions.InvalidData
```

It looks like something's gone wrong with the new battery-related stuff.  Would it be helpful if I got you a sanitized debug log from my script that's doing the call?

Here is the last line that got traced (sanitized, perhaps excessively so, since I wasn't sure what this data was):
DEBUG:locationsharinglib.Person:[None, [None, [None, -xxxx.xxxx, xxx.xxxx], xxxxx, xx, 'xxx My Address xxx', None, 'US', -xxxx], None, None, None, None, [None, None, None, None], None, None, None, None, None, None, None]

I think this person might've been me (it had my current location, and there's no name listed, which is consistent with what I've seen for my entry in get_all_people()...I'm assuming that's the way it's supposed to be).

Let me know if there's anything else I can do.

**Comment by costastf** [comment]
Could you please give v.3.0.6 a spin and let me know how it works for you? Also i have fixed a small bug I had with the debbug logging on the cli. I would be interested to know why that does not work for you and try to fix it.

**Comment by WillDHB** [comment]
Sorry for being slow to respond.  Updating did the trick.  To clarify, my problem with the cli wasn't the logging; I just couldn't authenticate.  I'm actually operating under the assumption that it's related to 2FA, but haven't really dug into it, since I've just been stealing cookies from my browser.

**Comment by costastf** [comment]
Well, the important thing is that it works for you so, closing this.
